package com.example.be_electronic_components_website.common;

public class Message {

    // LOGIN
    public static String VALIDATION_EMAIL_ERROR001 = "VALIDATION_EMAIL_ERROR001";
    public static String VALIDATION_EMAIL_ERROR002 = "VALIDATION_EMAIL_ERROR002";
    public static String VALIDATION_PASSWORD_ERROR001 = "VALIDATION_PASSWORD_ERROR001";
    public static String VALIDATION_PASSWORD_ERROR002 = "VALIDATION_PASSWORD_ERROR002";
    public static String LOGIN_SUCCESS = "LOGIN_SUCCESS";
    public static String LOGIN_ERROR001 = "LOGIN_ERROR001";

    // REGISTER
    public static String VALIDATION_NAME_ERROR001 = "VALIDATION_NAME_ERROR001";
    public static String VALIDATION_NAME_ERROR002 = "VALIDATION_EMAIL_ERROR002";
    public static String VALIDATION_EMAIL_ERROR003 = "VALIDATION_EMAIL_ERROR003";
    public static String VALIDATION_ADDRESS_ERROR001 = "VALIDATION_ADDRESS_ERROR001";
    public static String VALIDATION_PHONENUMBER_ERROR001 = "VALIDATION_PHONENUMBER_ERROR001";
    public static String VALIDATION_PHONENUMBER_ERROR002 = "VALIDATION_PHONENUMBER_ERROR002";
    public static String REGISTER_SUCCESS = "REGISTER_SUCCESS";
    public static String REGISTER_ERROR001 = "LOGIN_ERROR001";


}
