package com.poly.ecommercestore.common;

public class Message {
    // LOGIN
    public static String VALIDATION_EMAIL_ERROR001 = "VALIDATION_EMAIL_ERROR001";
    public static String VALIDATION_EMAIL_ERROR002 = "VALIDATION_EMAIL_ERROR002";
    public static String VALIDATION_PASSWORD_ERROR001 = "VALIDATION_PASSWORD_ERROR001";
    public static String VALIDATION_PASSWORD_ERROR002 = "VALIDATION_PASSWORD_ERROR002";
    public static String LOGIN_SUCCESS = "LOGIN_SUCCESS";
    public static String LOGIN_ERROR001 = "LOGIN_ERROR001";

    //EMPLOYEE

    // REGISTER
    public static String VALIDATION_NAME_ERROR001 = "VALIDATION_NAME_ERROR001";
    public static String VALIDATION_NAME_ERROR002 = "VALIDATION_NAME_ERROR002";
    public static String VALIDATION_EMAIL_ERROR003 = "VALIDATION_EMAIL_ERROR003";
    public static String VALIDATION_ADDRESS_ERROR001 = "VALIDATION_ADDRESS_ERROR001";
    public static String VALIDATION_PHONENUMBER_ERROR001 = "VALIDATION_PHONENUMBER_ERROR001";
    public static String VALIDATION_PHONENUMBER_ERROR002 = "VALIDATION_PHONENUMBER_ERROR002";
    public static String REGISTER_SUCCESS = "REGISTER_SUCCESS";
    public static String REGISTER_ERROR001 = "REGISTER_ERROR001";

    //RESET PASSWORD
    public static String RESET_PASSWORD_ERROR001 = "RESET_PASSWORD_ERROR001";
    public static String RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";

    //UPDATE USER
    public static String UPDATE_USER_ERROR001 = "UPDATE_USER_ERROR001";
    public static String UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

    //UPDATE PASSWORD
    public static String UPDATE_PASSWORD_CONFIRM_ERROR001 = "UPDATE_USER_ERROR001";
    public static String UPDATE_PASSWORD_ERROR001 = "UPDATE_USER_ERROR001";
    public static String UPDATE_PASSWORD_SUCCESS = "UPDATE_USER_SUCCESS";

    //UPDATE STATUS
        public static String UPDATE_STATUS_USER_ERROR001 = "UPDATE_STATUS_USER_ERROR001";
    public static String UPDATE_STATUS_USER_SUCCESS = "UPDATE_STATUS_USER_SUCCESS";


    // CART
    public static String VALIDATION_QUANTITY_CART_ERROR001 = "VALIDATION_QUANTITY_CART_ERROR001";
    public static String VALIDATION_ADD_CART_ERROR001 = "VALIDATION_ADD_CART_ERROR001";
    public static String VALIDATION_UPDATE_CART_ERROR001 = "VALIDATION_UPDATE_CART_ERROR001";
    public static String ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
    public static String UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
    public static String DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
    public static String VALIDATION_DELETE_CART_ERROR001 = "VALIDATION_DELETE_CART_ERROR001";

    //EVALUATION
    public static String VALIDATION_EVALUATE_ERROR001 = "VALIDATION_EVALUATE_ERROR001";
    public static String EVALUATION_ERROR001 = "EVALUATION_ERROR001";
    public static String EVALUATION_SUCCESS = "EVALUATION_SUCCESS";

    //ORDER
    public static String VALIDATION_DETAIL_ORDER_ERROR001 = "VALIDATION_DETAIL_ORDER_ERROR001";
    public static String VALIDATION_ADDRESS_ORDER_ERROR001 = "EVALUATION_ADDRESS_ORDER_ERROR001";
    public static String VALIDATION_TELEPHONE_ORDER_ERROR001 = "EVALUATION_TELEPHONE_ORDER_ERROR001";
    public static String VALIDATION_TELEPHONE_ORDER_ERROR002 = "EVALUATION_TELEPHONE_ORDER_ERROR002";
    public static String VALIDATION_SHIPPING_UNIT_ORDER_ERROR001 = "EVALUATION_SHIPPING_UNIT_ORDER_ERROR001";
    public static String VALIDATION_PAYMENT_ORDER_ERROR001 = "EVALUATION_PAYMENT_ORDER_ERROR001";
    public static String VALIDATION_QUANTITY_ERROR001 = "Số lượng tồn không đủ";

    public static String ORDER_SUCCESS = "ORDER_SUCCESS";
    public static String ORDER_ERROR001 = "ORDER_ERROR001";

    public static String VALIDATION_CANCELED_ORDER_ERROR001 = "EVALUATION_CANCELED_ORDER_ERROR001";
    public static String CANCELED_ORDER_SUCCESS = "EVALUATION_SUCCESS";

    public static String VALIDATION_CONFIRMED_ORDER_ERROR001 = "VALIDATION_CONFIRMED_ORDER_ERROR001";
    public static String CONFIRMED_ORDER_SUCCESS = "CONFIRMED_ORDER_SUCCESS";

    public static String VALIDATION_DELIVERY_ORDER_ERROR001 = "VALIDATION_DELIVERY_ORDER_ERROR001";
    public static String DELIVERY_ORDER_SUCCESS = "DELIVERY_ORDER_SUCCESS";

    public static String VALIDATION_DELIVERED_ORDER_ERROR001 = "VALIDATION_DELIVERED_ORDER_ERROR001";
    public static String DELIVERED_ORDER_SUCCESS = "DELIVERED_ORDER_SUCCESS";


    // IMPORT
    public static String VALIDATION_DETAIL_IMPORT_ERROR001 = "VALIDATION_DETAIL_IMPORT_ERROR001";
    public static String VALIDATION_NAME_IMPORT_ERROR001 = "VALIDATION_NAME_IMPORT_ERROR001";
    public static String VALIDATION_SUPPLIER_IMPORT_ERROR001 = "VALIDATION_SUPPLIER_IMPORT_ERROR001";
    public static String VALIDATION_IMPORT_ERROR001 = "VALIDATION_IMPORT_ERROR001";
    public static String VALIDATION_COMPLETE_IMPORT_ERROR001 = "VALIDATION_COMPLETE_IMPORT_ERROR001";
    public static String IMPORT_SUCCESS = "IMPORT_SUCCESS";
    public static String COMPLETE_IMPORT_SUCCESS = "COMPLETE_IMPORT_SUCCESS";

    // PAYMENT
    public static String VALIDATION_NAME_PAYMENT_ERROR001 = "VALIDATION_DETAIL_ORDER_ERROR001";
    public static String ADD_PAYMENT_SUCCESS = "ORDER_SUCCESS";
    public static String ADD_PAYMENT_ORDER_ERROR001 = "EVALUATION_ADDRESS_ORDER_ERROR001";
    public static String UPDATE_PAYMENT_SUCCESS = "ORDER_SUCCESS";
    public static String UPDATE_PAYMENT_ORDER_ERROR001 = "EVALUATION_ADDRESS_ORDER_ERROR001";
    public static String DELETE_PAYMENT_SUCCESS = "ORDER_SUCCESS";
    public static String DELETE_PAYMENT_ORDER_ERROR001 = "EVALUATION_ADDRESS_ORDER_ERROR001";

    //PRODUCT
    public static String VALIDATION_NAME_PRODUCT_ERROR001 = "VALIDATION_NAME_PRODUCT_ERROR001";
    public static String VALIDATION_TAX_PRODUCT_ERROR001 = "VALIDATION_TAX_PRODUCT_ERROR001";
    public static String VALIDATION_SUPPLIER_PRODUCT_ERROR001 = "VALIDATION_SUPPLIER_PRODUCT_ERROR001";
    public static String VALIDATION_CATEGORY_PRODUCT_ERROR001 = "VALIDATION_CATEGORY_PRODUCT_ERROR001";
    public static String VALIDATION_FEATURE_PRODUCT_ERROR001 = "VALIDATION_FEATURE_PRODUCT_ERROR001";
    public static String VALIDATION_CONTENTS_PRODUCT_ERROR001 = "VALIDATION_CONTENTS_PRODUCT_ERROR001";
    public static String VALIDATION_PRICE_PRODUCT_ERROR001 = "VALIDATION_PRICE_PRODUCT_ERROR001";
    public static String VALIDATION_IMAGE_PRODUCT_ERROR001 = "VALIDATION_IMAGE_PRODUCT_ERROR001";
    public static String VALIDATION_SPECIFICATION_PRODUCT_ERROR001 = "VALIDATION_SPECIFICATION_PRODUCT_ERROR001";
    public static String VALIDATION_PRODUCT_ALREADY_EXIST_ERROR001 = "VALIDATION_PRODUCT_ALREADY_EXIST_ERROR001";


    public static String ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
    public static String ADD_PRODUCT_ERROR001 = "ADD_PRODUCT_ORDER_ERROR001";
    public static String UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
    public static String UPDATE_PRODUCT_ERROR001 = "UPDATE_PRODUCT_ORDER_ERROR001";
    public static String DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
    public static String DELETE_PRODUCT_ERROR001 = "DELETE_PRODUCT_ORDER_ERROR001";

    //SHIPPING UNIT
    public static String VALIDATION_NAME_SHIPPING_UNIT_ERROR001 = "VALIDATION_NAME_SHIPPING_UNIT_ERROR001";
    public static String VALIDATION_EMAIL_SHIPPING_UNIT_ERROR001 = "VALIDATION_EMAIL_SHIPPING_UNIT_ERROR001";
    public static String VALIDATION_TELEPHONE_SHIPPING_UNIT_ERROR001 = "VALIDATION_TELEPHONE_SHIPPING_UNIT_ERROR001";
    public static String VALIDATION_ADDRESS_SHIPPING_UNIT_ERROR001 = "VALIDATION_ADDRESS_SHIPPING_UNIT_ERROR001";
    public static String VALIDATION_TELEPHONE_SHIPPING_UNIT_ERROR002 = "VALIDATION_TELEPHONE_SHIPPING_UNIT_ERROR002";

    public static String ADD_SHIPPING_UNIT_SUCCESS = "ADD_SHIPPING_UNIT_SUCCESS";
    public static String ADD_SHIPPING_UNIT_ERROR001 = "ADD_SHIPPING_UNIT_ERROR001";
    public static String UPDATE_SHIPPING_UNIT_SUCCESS = "UPDATE_SHIPPING_UNIT_SUCCESS";
    public static String UPDATE_SHIPPING_UNIT_ERROR001 = "UPDATE_SHIPPING_UNIT_ERROR001";
    public static String DELETE_SHIPPING_UNIT_SUCCESS = "DELETE_SHIPPING_UNIT_SUCCESS";
    public static String DELETE_SHIPPING_UNIT_ERROR001 = "DELETE_SHIPPING_UNIT_ERROR001";

    //SUPPLIER
    public static String VALIDATION_NAME_SUPPLIER_ERROR001 = "VALIDATION_NAME_SUPPLIER_ERROR001";
    public static String VALIDATION_EMAIL_SUPPLIER_ERROR001 = "VALIDATION_EMAIL_SUPPLIER_ERROR001";
    public static String VALIDATION_TELEPHONE_SUPPLIER_ERROR001 = "VALIDATION_TELEPHONE_SUPPLIER_ERROR001";
    public static String VALIDATION_ADDRESS_SUPPLIER_ERROR001 = "VALIDATION_ADDRESS_SUPPLIER_ERROR001";
    public static String VALIDATION_TELEPHONE_SUPPLIER_ERROR002 = "VALIDATION_TELEPHONE_SUPPLIER_ERROR002";

    public static String ADD_SUPPLIER_SUCCESS = "ADD_SUPPLIER_SUCCESS";
    public static String ADD_SUPPLIER_ERROR001 = "ADD_SUPPLIER_ERROR001";
    public static String UPDATE_SUPPLIER_SUCCESS = "UPDATE_SUPPLIER_SUCCESS";
    public static String UPDATE_SUPPLIER_ERROR001 = "UPDATE_SUPPLIER_ERROR001";
    public static String DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";
    public static String DELETE_SUPPLIER_ERROR001 = "DELETE_SUPPLIER_ERROR001";

}